### ISSUE TITLE
Changing the datepicker value by manually typing date creates issues

### ISSUE THREAD

**Issue by genericarati** [elm-community/elm-datepicker#62] opened 2017-10-16 20:07 UTC
Hi,

We have added a datepicker on our webpage which is defaulted to today's date. When I start clearing the date value using keyboard (using backspace button or by start typing the date) , date picker does let me pick the new date value, but does not display the newly selected value in the datepicker. Model changes with new dates selected, but datepicker does not reflect the change.

**Comment by bbqbaron** [comment] 2017-10-21 16:17
Hey, thanks for the report. I think I've managed to reproduce the issue too, though with slightly different steps. It seems to be due to the use of `defaultValue` (itself recently introduced in #58 to fix an issue with Elm overloading on quickly typed input text). The logic in the code seems fine, but it seems like the `input`'s `value` _property_ is not updating, even though its `value` _attribute_ is. The property remains stale, and thus picking does not update the text!

This is pretty arcane/strange. I'm not yet sure what causes the property to be retained, even when I try to force `keyed` to replace the element. 

If I revert `defaultValue` to `value`, _this_ problem clears up, but I don't want to undo the PR just yet. @mbylstra, if you have a moment, did you run into anything during your investigation of `defaultValue` that might explain this? Not blaming you for the change or anything; it's a pretty subtle problem :).

**Comment by mbylstra** [comment] 2017-10-22 00:58
Hi, I saw this issue when it was opened and did immediately think PR #58 must have introduced it. However, when I checked out an earlier version locally and rebuilt and tested the example in `examples/simple`, I was still seeing the problem, so I assumed this was a prior issue. Turns out I must have been looking at the Browser's cached version of #58 :sweat:

I'm happy for you to revert #58 to fix this issue. This seems like a worse issue than the one #58 attempted to solve. I've opened issue #63 to keep track of the dropped characters issue.

It'd be great if there were regression tests, but these problems are so browser specific that something like Browser Stack would be required. Browser Stack is free for open source projects but would likely require considerable effort to set up and maintain. I'll have a look into it though.

I'll see if I can find a better solution for issue #63.

**Comment by zwilias** [comment] 2017-10-22 10:18
For what it's worth, you can augment the workaround in #58 with the same idea used for resetting value in the original workaround - using a counter that is updated when a date is actually selected, which will the render a new node for the input field, hence re-applying the `defaultValue`. 

This is unlikely to play nice with `focus`, though. 🤔

**Comment by bbqbaron** [comment] 2017-10-31 21:07
I believe this has been fixed in #65. @genericarati do you mind confirming on version `7.2.3`?

**Comment by bbqbaron** [comment] 2017-10-31 21:07
(Provisionally closing)

**Closed by bbqbaron** 2017-10-31 21:07 UTC
Labels: bug
