### ISSUE TITLE
Manually entering date behaves poorly with subscriptions.

### ISSUE THREAD

**Issue by jnoggle** [elm-community/elm-datepicker#68] opened 2017-11-06 23:45 UTC
Hello, I wanted to bring attention to an issue, likely related to release 7.2.3 and Issue #62.

If the user is typing a date manually into the date-picker input and a subscription event fires before the date is able to be parsed, the intermediate date is erased and replaced with the last selected date. I've made a short example in Ellie demonstrating this behavior.

https://ellie-app.com/ss9GZhCg2a1/0

To reproduce: 1) Select a date with the mouse. 2) Re-focus the input. 3) Delete the text in the input by a character. 4) Wait for the Tick event to fire.

I believe this is caused by the subscription event triggering a re-draw of the input element. This also occurs if a scroll event elsewhere on the page is triggered. My best guess is that the removal of the `inputText` value is the culprit behind the behavior, as the input text isn't be stored until it is parse-able as a date.

I'll happily start working to find a solution if that's alright.

**Comment by bbqbaron** [comment] 2017-11-07 02:05
That explanation makes perfect sense; in hindsight it should have been obvious to me that removing a state var for current input text was foolhardy. Sorry for letting that through. A fix would be welcome. If any background would help, this saga started in #58, which was designed to fix Elm's basic incapacity to handle rapidly entered inputs asynchronously. You may need to reintroduce that bug into the app, although I'd be thrilled to see how to satisfy everyone! 😄 Thanks for the report.

**Comment by mbylstra** [comment] 2017-11-12 04:13
Apologies for introducing this - it's not something I thought of. 

Yes, I think the only step forward is to disable the test for https://github.com/elm-community/elm-datepicker/issues/63, and re-introduce the text input state (which causes the problem in #63).

I've created the PR #70 which comments out the rapid input test and adds a test that simulates the subscriptions issue. Hopefully as the test suite becomes more fleshed out, the chance of introducing regressions will lessen (I introduced the test suite after the first regression I was responsible for).

#63 remains a problem for us - we'll have no way of deploying code for our entire organisation, as it causes tests to break. It's much less of an issue if you don't have acceptance tests - it's unlikely users would type fast enough that they would notice. I may have to lock to present version - we happen to not have any subscriptions running, so it works for us (at least for now). I have an idea for another solution (back to the drawing board), but I am wary of creating yet another regression. Hopefully the root issue https://github.com/elm-lang/virtual-dom/issues/107 will be fixed in 0.19.

**Comment by mbylstra** [comment] 2017-11-12 04:26
Actually, the new test I wrote breaks because of #63 :facepalm:. I need to head out but I'll rewrite the new test so that it enters text slowly later.

**Comment by mbylstra** [comment] 2017-11-12 05:07
I've updated the tests - they should be reliable now.

**Comment by bbqbaron** [comment] 2017-11-13 17:12
Whew! Merged #69 and #70 together and released as 7.2.4. Thanks to you both for tackling this.

**Closed by bbqbaron** 2017-11-13 17:12 UTC
