### ISSUE TITLE
picker doesn't necessarily close when a date is picked

### ISSUE THREAD

**Issue by 97jaz** [elm-community/elm-datepicker#42] opened 2017-05-01 23:22 UTC
If you open the datepicker and select a date with your mouse, then, while the picker is still open, backspace and delete the chosen date in the input. Even when you blur the field afterwards, you won't get a `Changed` date event. I wonder if the `Text` and `Submit` text messages need to be combined.

**Comment by bbqbaron** [comment] 2017-05-02 00:38
Hm! Sorry, dumb question, but doesn't the datepicker close when you pick a date? It's only `forceOpen` between a mouse-down and a mouse-up, isn't it? How is it possible to mouse-pick a date without it promptly closing? I can do some similar sorts of things, like picking a date and typing in the field, but I seem to get the change events I expect in the cases I make up.

Would you mind exporting the debugger history of your example so I can try it out?

**Comment by 97jaz** [comment] 2017-05-02 01:00
Heh, I was wondering if it was supposed to close. It's likely then that there's some interaction with other click handling. I'll take a look at that tomorrow. 

I can't provide the actual code, since it's my company's, but if it turns out not to be what I said in the last paragraph, I'll try to put together a minimal example.

**Comment by 97jaz** [comment] 2017-05-02 15:57
Okay, nothing is really jumping out at me. I am collecting clicks (by subscribing to `Mouse.clicks` from elm-lang/mouse), but I don't think that should interfere with this, since the datepicker will see those DOM events first.

Hrm. Well, the sequence of `Msg`s that I see from the picker is:
- Focus (opening the picker)
- Focus
- MouseDown
- Blur
- MouseUp
- Pick
- Focus
- Focus

So, I understand that `Pick` results in `open = False`, but the subsequent `Focus` messages are what's keeping the picker open, right?

**Comment by 97jaz** [comment] 2017-05-02 16:05
Ah -- I think I may know what it is. The input is wrapped in an HTML `label`, and when I pick a date, the event will continue to bubble [http://package.elm-lang.org/packages/elm-lang/mouse/latest]. So the label gets a click, which re-opens the menu. I'm going to test this now, but I'm pretty sure that's what's happening.

**Comment by 97jaz** [comment] 2017-05-02 16:07
Yep, that is exactly what's happening. Maybe the click that results in a `Pick` should swallow the DOM event?

**Comment by bbqbaron** [comment] 2017-05-16 11:02
I'm doing a round of updates and have worked my way back to this. Something is weird, because I can't reproduce this behavior by clicking on any particular date. The other odd part is that pick clicks are eventually stopped by the `onPicker` call roughly [here](https://github.com/elm-community/elm-datepicker/blob/5.0.1/src/DatePicker.elm#L487), aren't they? The click on the actual day `td` does propagate, but shouldn't survive outside the calendar itself.

If you can find an otherwise-harmless fix that seems to fix the behavior on your end, could you PR it or at least sketch it out? I might even be able to derive the behavior necessary to reproduce it, although it could also just be unfathomable.

**Comment by 97jaz** [comment] 2017-05-16 12:43
I can try to reproduce this in a small example. (I've since worked around the problem in my actual code by pulling the datepicker out of the label.)

**Comment by 97jaz** [comment] 2017-05-16 12:43
(Oh, and when I reproduce, I can try to fix it too, of course.)

**Comment by bbqbaron** [comment] 2017-05-16 12:46
Thank you!

**Comment by 97jaz** [comment] 2017-05-17 02:41
Example: https://ellie-app.com/3cNf77kwDY4a1/0

**Closed** 2017-05-19 01:32 UTC
